

root@csst-06:/home/ubuntu/laspdev# 
root@csst-06:/home/ubuntu/laspdev# python /home/ubuntu/laspdev/utility/setup_lasp.py d10
d10
ip:12.0.0.12
node:b
)2> LASPVIN no peer to subscribe Case 1 
 lasp_peer_service:join('a@12.0.0.11').
ok
(b@12.0.0.12)3> 15:29:53.010 [error] LASPVIN received find_sub Id: "c@10.0.0.13c1" From: 'a@12.0.0.11' 
15:29:53.011 [error] LASPVIN Request forwarded~n
LASPVIN no peer to subscribe Case 1 
 15:29:53.082 [error] LASPVIN received find_sub Id: "c@10.0.0.13c1" From: 'a@12.0.0.11' 
15:29:53.082 [error] LASPVIN Request forwarded~n
15:29:53.239 [error] LASPVIN received find_sub Id: "c@10.0.0.13c1" From: 'd@12.0.0.14' 
15:29:53.239 [error] LASPVIN Request forwarded~n
15:29:53.293 [error] LASPVIN received find_sub Id: "c@10.0.0.13c1" From: 'd@12.0.0.14' 
15:29:53.293 [error] LASPVIN Request forwarded~n
15:29:55.339 [error] LASPVIN received find_sub Id: "c@10.0.0.13c1" From: 'c@12.0.0.13' 
15:29:55.339 [error] LASPVIN Request forwarded~n
15:30:00.033 [error] LASPVIN received find_sub Id: "c@12.0.0.13c1" From: 'a@12.0.0.11' 
15:30:00.033 [error] LASPVIN found the peer at "2020-06-06T15:30:00.336" for ID: "c@12.0.0.13c1" ToNode: 'c@10.0.0.13' 
15:30:00.040 [error] LASPVIN Peer 'c@12.0.0.13' is Source of Req.. Skipping 
15:30:00.075 [error] LASPVIN received find_sub Id: "c@12.0.0.13c1" From: 'd@12.0.0.14' 
LASPVIN no peer to subscribe Case 1 
 15:30:03.089 [error] LASPVIN received find_sub Id: "c@12.0.0.13c1" From: 'c@12.0.0.13' 
15:30:03.330 [error] LASPVIN found the peer at "2020-06-06T15:30:03.330" for ID: "c@10.0.0.13c1" ToNode: 'c@12.0.0.13' 
15:30:03.330 [error] LASPVIN False call
15:30:10.030 [error] LASPVIN found the peer at "2020-06-06T15:30:10.306" for ID: "c@10.0.0.13c1" ToNode: 'a@12.0.0.11' 
15:30:10.030 [error] LASPVIN found the peer at "2020-06-06T15:30:10.306" for ID: "c@12.0.0.13c1" ToNode: 'a@12.0.0.11' 
15:31:03.064 [error] LASPVIN Received delta From='c@12.0.0.13' at TimeStamp="2020-06-06T15:31:03.643" Took=40231 microseconds 
15:31:28.545 [warning] global: 'b@12.0.0.12' failed to connect to 'a@10.0.0.11'
15:31:28.546 [warning] global: 'b@12.0.0.12' failed to connect to 'a@11.0.0.11'
