

root@csst-06:/home/ubuntu/laspdev# 
root@csst-06:/home/ubuntu/laspdev# python /home/ubuntu/laspdev/utility/setup_lasp.py d2
d2
ip:10.0.0.12
node:b
)2> LASPVIN no peer to subscribe Case 1 
 lasp_peer_service:join('a@10.0.0.11').
ok
(b@10.0.0.12)3> LASPVIN no peer to subscribe Case 1 
 15:29:52.995 [error] LASPVIN received find_sub Id: "c@10.0.0.13c1" From: 'c@10.0.0.13' 
15:29:52.997 [error] LASPVIN Request forwarded~n
15:29:53.062 [info] Connection cache miss for node: ['c@11.0.0.13']
15:29:53.062 [info] Node not yet connected when sending {forward_message,lasp_delta_based_synchronization_backend,{'$gen_cast',{find_sub_aq_lock,"c@10.0.0.13c1",'b@10.0.0.12'}}} to ['c@11.0.0.13'] from 'b@10.0.0.12'!
15:29:53.344 [error] LASPVIN Rate updated already ~n
15:29:53.344 [info] Connection cache miss for node: ['c@11.0.0.13','c@12.0.0.13']
15:29:53.344 [info] Node not yet connected when sending {forward_message,lasp_delta_based_synchronization_backend,{'$gen_cast',{find_sub_aq_lock,"c@10.0.0.13c1",'b@10.0.0.12'}}} to ['c@11.0.0.13','c@12.0.0.13'] from 'b@10.0.0.12'!
15:29:55.331 [error] LASPVIN False call
15:30:25.390 [error] LASPVIN Received delta From='c@10.0.0.13' at TimeStamp="2020-06-06T15:30:25.390" Took=42004 microseconds 
15:30:44.064 [error] LASPVIN Received delta From='a@10.0.0.11' at TimeStamp="2020-06-06T15:30:44.644" Took=375 microseconds 
15:31:10.366 [error] LASPVIN Received delta From='c@10.0.0.13' at TimeStamp="2020-06-06T15:31:10.366" Took=1090 microseconds 
